"""empty message

Revision ID: 3570b390ab1f
Revises: 61e92f30ab39
Create Date: 2022-08-11 10:14:12.963158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3570b390ab1f'
down_revision = '61e92f30ab39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('subreddit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'subreddit')
    # ### end Alembic commands ###
