"""empty message

Revision ID: 61e92f30ab39
Revises: 395344e162e5
Create Date: 2022-08-10 14:32:33.010452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "61e92f30ab39"
down_revision = "395344e162e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    submissionmediatype = postgresql.ENUM(
        "text", "image", "video", name="submissionmediatype"
    )
    submissionmediatype.create(op.get_bind())
    op.add_column(
        "submission",
        sa.Column(
            "media_type",
            sa.Enum("text", "image", "video", name="submissionmediatype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "media_type")
    submissionmediatype = postgresql.ENUM(
        "text", "image", "video", name="submissionmediatype"
    )
    submissionmediatype.drop(op.get_bind())
    # ### end Alembic commands ###
